version: "3.7"

services:
  backofficeapp:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: backoffice-app
    environment:
      - SPRING_PROFILES_ACTIVE=homol
      - POSTGRES_USER=shapeupadmin
      - POSTGRES_PASSWORD=#Gfgrupo7
      - POSTGRES_DB=shapeup
      - POSTGRES_URL=jdbc:postgresql://shapeupdb.postgres.database.azure.com:5432/shapeup?user=shapeupadmin&password=#Gfgrupo7&sslmode=require
    ports:
      - "7003:7003"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql